language: node_js
node_js:
- stable
script:
- npm run build
- echo "theco2fight.com" > build/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: build/
